version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_smartShop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # mot de passe root
      MYSQL_DATABASE: smartShop_db  # base créée automatiquement
      MYSQL_USER: mohsen
      MYSQL_PASSWORD: mohsen123
    ports:
      - "3306:3306"
    volumes:
      - smartshop_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_smartShop
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  smartshop_data:
